apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  annotations:
    argo.octopus.com/project: "argocd"
    argo.octopus.com/environment: "development-tf-test"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
